title: Karthik Premaram
logo: /assets/img/pic2.png
description: Projects portfolio
#show_downloads: true
theme: jekyll-theme-minimal
email: premaramkarthik@gmail.com
linkedin: www.linkedin.com/in/karthik-premaram

